apiVersion: v1
kind: Service
metadata:
  name: service-web
  namespace: soxnaamycoulibaly-dev
spec:
  selector:
    kubevirt.io/domain: vm2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
