name: Deploy to OpenShift
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true

    - name: Apply Configuration
      run: |
        oc apply -f 02-services/mysql.yaml
        oc apply -f web-service.yaml
        oc apply -f 03-reseau/network-policy.yaml
        oc apply -f 03-reseau/route.yaml
        oc apply -f 01-virtualisation/vm2.yaml
        oc apply -f 01-virtualisation/fedora.yaml
